openapi: 3.1.0
info:
  title: Market GAP Analysis API
  version: 1.0.0
paths:
  /start_market_gap:
    post:
      summary: Start Market GAP Analysis
      operationId: startMarketGap
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - session_id
                - email
                - files
              properties:
                session_id:
                  type: string
                  description: Unique session identifier (e.g., Temp_YYYYMMDD_email)
                email:
                  type: string
                  description: User email address
                files:
                  type: array
                  description: List of input files and their metadata
                  items:
                    type: object
                    required:
                      - file_name
                      - file_url
                      - file_type
                    properties:
                      file_name:
                        type: string
                      file_url:
                        type: string
                      file_type:
                        type: string
      responses:
        "200":
          description: Market GAP analysis started successfully
        "500":
          description: Internal server error
